language: php

php:
  - "7.4"
  - "8.0"

before_install:
  # Install yara
  - sudo apt-get update
  - sudo apt-get install -y yara

install:
  # Install Composer dependencies, if any
  - if [ -f composer.json ]; then composer install; fi

script:
  # PHP syntax validation for all PHP files
  - find . -type f -name "*.php" -exec php -l {} \;

  # Run yara scan if rule file exists
  - if [ -f wordpress-threats.yar ]; then
      echo "Running YARA scan...";
      yara -r rules/wordpress-threats.yar test-payloads/;
    else
      echo "No YARA rules file found, skipping scan.";
    fi
