language: php

php:
  - "7.4"
  - "8.0"

before_install:
  # Install yara
  - sudo apt-get update
  - sudo apt-get install -y yara

install:
  # Install Composer dependencies, if any
  - if [ -f composer.json ]; then composer install; fi

script:
  # PHP syntax validation for all PHP files
  - find . -type f -name "*.php" -exec php -l {} \;

  # Run yara scan and fail if there are any matches
  - |
    if [ -f wordpress-threats.yar ]; then
      echo "Running YARA scan...";
      SCAN_RESULT=$(yara -r wordpress-threats.yar test-payloads/)
      if [ -n "$SCAN_RESULT" ]; then
        echo "YARA scan failed! Threats detected:";
        echo "$SCAN_RESULT"
        exit 1
      else
        echo "YARA scan passed. No threats detected."
      fi
    else
      echo "No YARA rules file found, skipping scan."
    fi